name: Develop CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'demo/**'

jobs:
  develop-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn install

      - name: Build Website
        run: yarn build