# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ node-nuxtjs ]
  pull_request:
    types: [closed]
    branches:
      - node-nuxtjs

jobs:
  deploy:

    runs-on: ubuntu-latest
    name: Deploy to server
    steps:
      - name: Exec deploy script with SSH
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 8m
          host: ${{ secrets.ALIYUM_HOST }}
          username: ${{ secrets.ALIYUM_USER }}
          password: ${{ secrets.ALIYUM_PWD }}
          port: ${{secrets.ALIYUM_PORT }}
          # script: sh ${{ secrets.PATH }}/blog-front/.deploy/main.sh
          script: sh ../../.deploy/main.sh
